### ISSUE TITLE
ConvertToNetworkByteOrder and ComputerCheckSum order reversed

### ISSUE THREAD

**Issue by JustinLovesCompsci** [JustinLovesCompsci/Network_Protocol#1]
In prepareToTransmit(packet_t*) method: the order is reversed. We agreed that we compute the checksum before we convert the packet to network byte order. Please fix the bug immediately @stevenyy 

Code:
/\* Prepare for UDP
- converts all necessary fields to network byte order
- computes and writes the checksum to the cksum field
  _/
  void prepareToTransmit(packet_t_ packet) {
  int packetLength = (int) (packet->len);
  convertToNetworkByteOrder(packet);
  packet->cksum = computeChecksum(packet, packetLength);
  }

**Comment by lawrencelin** [comment]
Fixed.
