### ISSUE TITLE
EOF handling issue

### ISSUE THREAD

**Issue by lawrencelin** [JustinLovesCompsci/Network_Protocol#10]
According to reference, this is the sequence of handling EOF:
1. User A writes EOF (by pressing ctrl+d)
2. User B writes EOF
3. Connection on both sides closes

What we have right now:
1. User A writes EOF
2. A receives ack from B
3. Connection on side A closes, but B remains open

**Comment by JustinLovesCompsci** [comment]
Working on this

**Comment by JustinLovesCompsci** [comment]
Both connection closes. What we have now is the following:
1. User A writes EOF (by pressing ctrl+d)
2. User B writes EOF
3. Connection on both sides closes, but B has an assertion failed error. 
   *error seems to appear in rel_destory(..). Please take a look at this @lawrencelin 

Log is below (in B):
IN rel_recvpkt
Packet seqno: 2, expecting: 2
seqnoLastReceived = 2, seqnoLastRead = 1, windowSize = 1
append node to last received with seqno 2
rel_output: read EOF from sender
IN rel_destroy
reliable: rlib.c:238: conn_input: Assertion `!c->delete_me' failed.
Aborted (core dumped)

Log is below (in A):
read EOF from input
IN rel_destroy

**Comment by lawrencelin** [comment]
Try testing it against reference.

**Comment by JustinLovesCompsci** [comment]
From Benson:
"for example you still need to set the appropriate sequence numbers and acknowledgement numbers. Set the appropriate checksum.
if you send an EOF packet with just len and checksum, then the receiver wouldn't accept it."

Seems like the reference does not recognize the EOF packet from reliable. We shall set seqno, ackno and checksum right for EOF packets. How to do this? @lawrencelin

**Comment by lawrencelin** [comment]
I said that last night. EOF has correct seqno and ackno; not why we are having problem against reference.

**Comment by JustinLovesCompsci** [comment]
the reference does not recognize the EOF packet from reliable. It should close connection but stay online instead. How do you know EOF has correct seqno, ackno then?

**Comment by lawrencelin** [comment]
Use "./reliable -d 5555 localhost:6666" on one side and "./reference -d 6666 localhost:5555" on the other. It will display the info of all sending and receiving packets.

**Comment by JustinLovesCompsci** [comment]
it seems like we close connection too early before we sending back the last ACK for EOF

**Comment by JustinLovesCompsci** [comment]
Even though you run two ./reference programs and sent EOF from one to the other, both connections will not close.

They will only close IF both ends send EOF data packets to each other

**Comment by JustinLovesCompsci** [comment]
Solved and pushed

**Comment by JustinLovesCompsci** [comment]
Two reliable programs sending EOF to each other. rel_destory() gets called twice and caused double free error
