### ISSUE TITLE
Packet seqno & expecting same value

### ISSUE THREAD

**Issue by stevenyy** [JustinLovesCompsci/Network_Protocol#12]
For example, when testing using two terminals and running ./reliable against each other, one end has Packet seqno: 4, expecting: 4
![screen shot 2015-04-06 at 2 54 09 pm](https://cloud.githubusercontent.com/assets/4335998/7010090/d0c59734-dc6c-11e4-8ef0-a788f206a97c.png)

**Comment by JustinLovesCompsci** [comment]
This behavior is expected
