### ISSUE TITLE
Received old ACKs counted as duplicates

### ISSUE THREAD

**Issue by JustinLovesCompsci** [JustinLovesCompsci/Network_Protocol#15]
in line 207:
        if (r->sending_window->seqno_last_packet_acked == pkt->ackno) {
            r->num_duplicated_ack_received++;
        }

what if pkt->ackno < r->sending_window->seqno_last_packet_acked? shall we also count it as a duplicate?

**Comment by lawrencelin** [comment]
I don't think so. If received an ACK with ack smaller than r->sending_window->seqno_last_packet_acked, there's no need for retranmission because seqno_last_packet_acked means all data packets before have been received and acknowledged by the receiver.

**Comment by JustinLovesCompsci** [comment]
Well, if received an old ACK, that means the network is congested. The previous ACK is not received in order before the last ACK. So we should slow down our sending rate
