### ISSUE TITLE
xmalloc in rel_create(..) Why??

### ISSUE THREAD

**Issue by JustinLovesCompsci** [JustinLovesCompsci/Network_Protocol#5]
I did a search on StackOverFlow, and xmalloc is regarded as a bad practice. One of the posts as below:

"xmalloc is a non-standard function that has the motto "succeed or die". If it fails to allocate memory it will terminate your program and print an error message to stderr.

The allocation itself is no different, only the behaviour in the case that no memory could be allocated.

Use malloc, since it's more friendly and standard."

Why are you @lawrencelin  using xmalloc in rel_create() then?

**Comment by lawrencelin** [comment]
xmalloc is given by the instructor. I didn't use it in my own code.
